// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.1
// source: proto/dosloader.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControllerCommand_Type int32

const (
	ControllerCommand_START  ControllerCommand_Type = 0
	ControllerCommand_PAUSE  ControllerCommand_Type = 1
	ControllerCommand_RESUME ControllerCommand_Type = 2
	ControllerCommand_STOP   ControllerCommand_Type = 3
)

// Enum value maps for ControllerCommand_Type.
var (
	ControllerCommand_Type_name = map[int32]string{
		0: "START",
		1: "PAUSE",
		2: "RESUME",
		3: "STOP",
	}
	ControllerCommand_Type_value = map[string]int32{
		"START":  0,
		"PAUSE":  1,
		"RESUME": 2,
		"STOP":   3,
	}
)

func (x ControllerCommand_Type) Enum() *ControllerCommand_Type {
	p := new(ControllerCommand_Type)
	*p = x
	return p
}

func (x ControllerCommand_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControllerCommand_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_dosloader_proto_enumTypes[0].Descriptor()
}

func (ControllerCommand_Type) Type() protoreflect.EnumType {
	return &file_proto_dosloader_proto_enumTypes[0]
}

func (x ControllerCommand_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControllerCommand_Type.Descriptor instead.
func (ControllerCommand_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{2, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type TestConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Users         int32                  `protobuf:"varint,4,opt,name=users,proto3" json:"users,omitempty"`
	Duration      string                 `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`                    // e.g. "60s"
	RampUp        string                 `protobuf:"bytes,6,opt,name=ramp_up,json=rampUp,proto3" json:"ramp_up,omitempty"`          // e.g. "10s"
	ThinkTime     string                 `protobuf:"bytes,7,opt,name=think_time,json=thinkTime,proto3" json:"think_time,omitempty"` // e.g. "500ms"
	Headers       map[string]string      `protobuf:"bytes,8,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timeout       string                 `protobuf:"bytes,9,opt,name=timeout,proto3" json:"timeout,omitempty"` // e.g. "30s"
	Body          []byte                 `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	Loops         int32                  `protobuf:"varint,11,opt,name=loops,proto3" json:"loops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConfig) Reset() {
	*x = TestConfig{}
	mi := &file_proto_dosloader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConfig) ProtoMessage() {}

func (x *TestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConfig.ProtoReflect.Descriptor instead.
func (*TestConfig) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{1}
}

func (x *TestConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestConfig) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TestConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TestConfig) GetUsers() int32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *TestConfig) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *TestConfig) GetRampUp() string {
	if x != nil {
		return x.RampUp
	}
	return ""
}

func (x *TestConfig) GetThinkTime() string {
	if x != nil {
		return x.ThinkTime
	}
	return ""
}

func (x *TestConfig) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *TestConfig) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *TestConfig) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *TestConfig) GetLoops() int32 {
	if x != nil {
		return x.Loops
	}
	return 0
}

type ControllerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControllerCommand_Type `protobuf:"varint,1,opt,name=type,proto3,enum=dosloader.ControllerCommand_Type" json:"type,omitempty"`
	Config        *TestConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerCommand) Reset() {
	*x = ControllerCommand{}
	mi := &file_proto_dosloader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerCommand) ProtoMessage() {}

func (x *ControllerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerCommand.ProtoReflect.Descriptor instead.
func (*ControllerCommand) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{2}
}

func (x *ControllerCommand) GetType() ControllerCommand_Type {
	if x != nil {
		return x.Type
	}
	return ControllerCommand_START
}

func (x *ControllerCommand) GetConfig() *TestConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ControllerCommand) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type MetricsData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Requests         int64                  `protobuf:"varint,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Successes        int64                  `protobuf:"varint,2,opt,name=successes,proto3" json:"successes,omitempty"`
	Failures         int64                  `protobuf:"varint,3,opt,name=failures,proto3" json:"failures,omitempty"`
	Timeouts         int64                  `protobuf:"varint,4,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	BytesSent        int64                  `protobuf:"varint,5,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived    int64                  `protobuf:"varint,6,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	RunningUsers     int64                  `protobuf:"varint,7,opt,name=running_users,json=runningUsers,proto3" json:"running_users,omitempty"`
	CompletedUsers   int64                  `protobuf:"varint,8,opt,name=completed_users,json=completedUsers,proto3" json:"completed_users,omitempty"`
	MinLatencyNs     int64                  `protobuf:"varint,9,opt,name=min_latency_ns,json=minLatencyNs,proto3" json:"min_latency_ns,omitempty"`
	MaxLatencyNs     int64                  `protobuf:"varint,10,opt,name=max_latency_ns,json=maxLatencyNs,proto3" json:"max_latency_ns,omitempty"`
	TotalLatencyNs   int64                  `protobuf:"varint,11,opt,name=total_latency_ns,json=totalLatencyNs,proto3" json:"total_latency_ns,omitempty"`
	HistogramBuckets map[int32]int64        `protobuf:"bytes,12,rep,name=histogram_buckets,json=histogramBuckets,proto3" json:"histogram_buckets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // bucket_index -> count
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsData) Reset() {
	*x = MetricsData{}
	mi := &file_proto_dosloader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsData) ProtoMessage() {}

func (x *MetricsData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsData.ProtoReflect.Descriptor instead.
func (*MetricsData) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{5}
}

func (x *MetricsData) GetRequests() int64 {
	if x != nil {
		return x.Requests
	}
	return 0
}

func (x *MetricsData) GetSuccesses() int64 {
	if x != nil {
		return x.Successes
	}
	return 0
}

func (x *MetricsData) GetFailures() int64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

func (x *MetricsData) GetTimeouts() int64 {
	if x != nil {
		return x.Timeouts
	}
	return 0
}

func (x *MetricsData) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *MetricsData) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *MetricsData) GetRunningUsers() int64 {
	if x != nil {
		return x.RunningUsers
	}
	return 0
}

func (x *MetricsData) GetCompletedUsers() int64 {
	if x != nil {
		return x.CompletedUsers
	}
	return 0
}

func (x *MetricsData) GetMinLatencyNs() int64 {
	if x != nil {
		return x.MinLatencyNs
	}
	return 0
}

func (x *MetricsData) GetMaxLatencyNs() int64 {
	if x != nil {
		return x.MaxLatencyNs
	}
	return 0
}

func (x *MetricsData) GetTotalLatencyNs() int64 {
	if x != nil {
		return x.TotalLatencyNs
	}
	return 0
}

func (x *MetricsData) GetHistogramBuckets() map[int32]int64 {
	if x != nil {
		return x.HistogramBuckets
	}
	return nil
}

type MetricsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics       *MetricsData           `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsPayload) Reset() {
	*x = MetricsPayload{}
	mi := &file_proto_dosloader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsPayload) ProtoMessage() {}

func (x *MetricsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsPayload.ProtoReflect.Descriptor instead.
func (*MetricsPayload) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{6}
}

func (x *MetricsPayload) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *MetricsPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsPayload) GetMetrics() *MetricsData {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type MetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{7}
}

func (x *MetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StartTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *TestConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestRequest) Reset() {
	*x = StartTestRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestRequest) ProtoMessage() {}

func (x *StartTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestRequest.ProtoReflect.Descriptor instead.
func (*StartTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{8}
}

func (x *StartTestRequest) GetConfig() *TestConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type StartTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTestResponse) Reset() {
	*x = StartTestResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTestResponse) ProtoMessage() {}

func (x *StartTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTestResponse.ProtoReflect.Descriptor instead.
func (*StartTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{9}
}

func (x *StartTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PauseTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTestRequest) Reset() {
	*x = PauseTestRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTestRequest) ProtoMessage() {}

func (x *PauseTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTestRequest.ProtoReflect.Descriptor instead.
func (*PauseTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{10}
}

type PauseTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTestResponse) Reset() {
	*x = PauseTestResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTestResponse) ProtoMessage() {}

func (x *PauseTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTestResponse.ProtoReflect.Descriptor instead.
func (*PauseTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{11}
}

func (x *PauseTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PauseTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResumeTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTestRequest) Reset() {
	*x = ResumeTestRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTestRequest) ProtoMessage() {}

func (x *ResumeTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTestRequest.ProtoReflect.Descriptor instead.
func (*ResumeTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{12}
}

type ResumeTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTestResponse) Reset() {
	*x = ResumeTestResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTestResponse) ProtoMessage() {}

func (x *ResumeTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTestResponse.ProtoReflect.Descriptor instead.
func (*ResumeTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{13}
}

func (x *ResumeTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResumeTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestRequest) Reset() {
	*x = StopTestRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestRequest) ProtoMessage() {}

func (x *StopTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestRequest.ProtoReflect.Descriptor instead.
func (*StopTestRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{14}
}

type StopTestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTestResponse) Reset() {
	*x = StopTestResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTestResponse) ProtoMessage() {}

func (x *StopTestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTestResponse.ProtoReflect.Descriptor instead.
func (*StopTestResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{15}
}

func (x *StopTestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopTestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WorkerHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHealthRequest) Reset() {
	*x = WorkerHealthRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHealthRequest) ProtoMessage() {}

func (x *WorkerHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHealthRequest.ProtoReflect.Descriptor instead.
func (*WorkerHealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{16}
}

type WorkerHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workers       []*WorkerInfo          `protobuf:"bytes,1,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHealthResponse) Reset() {
	*x = WorkerHealthResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHealthResponse) ProtoMessage() {}

func (x *WorkerHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHealthResponse.ProtoReflect.Descriptor instead.
func (*WorkerHealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{17}
}

func (x *WorkerHealthResponse) GetWorkers() []*WorkerInfo {
	if x != nil {
		return x.Workers
	}
	return nil
}

type WorkerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "ONLINE", "OFFLINE", "TESTING"
	LastHeartbeat int64                  `protobuf:"varint,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerInfo) Reset() {
	*x = WorkerInfo{}
	mi := &file_proto_dosloader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerInfo) ProtoMessage() {}

func (x *WorkerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerInfo.ProtoReflect.Descriptor instead.
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{18}
}

func (x *WorkerInfo) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *WorkerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkerInfo) GetLastHeartbeat() int64 {
	if x != nil {
		return x.LastHeartbeat
	}
	return 0
}

type JobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusRequest) Reset() {
	*x = JobStatusRequest{}
	mi := &file_proto_dosloader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusRequest) ProtoMessage() {}

func (x *JobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusRequest.ProtoReflect.Descriptor instead.
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{19}
}

type JobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "IDLE", "RUNNING", "PAUSED", "STOPPED", "COMPLETED"
	Config        *TestConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatusResponse) Reset() {
	*x = JobStatusResponse{}
	mi := &file_proto_dosloader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatusResponse) ProtoMessage() {}

func (x *JobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatusResponse.ProtoReflect.Descriptor instead.
func (*JobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{20}
}

func (x *JobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobStatusResponse) GetConfig() *TestConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *JobStatusResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type MetricsSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSubscription) Reset() {
	*x = MetricsSubscription{}
	mi := &file_proto_dosloader_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSubscription) ProtoMessage() {}

func (x *MetricsSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSubscription.ProtoReflect.Descriptor instead.
func (*MetricsSubscription) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{21}
}

type AggregatedMetrics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Timestamp      int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalRequests  int64                  `protobuf:"varint,2,opt,name=total_requests,json=totalRequests,proto3" json:"total_requests,omitempty"`
	TotalSuccesses int64                  `protobuf:"varint,3,opt,name=total_successes,json=totalSuccesses,proto3" json:"total_successes,omitempty"`
	TotalFailures  int64                  `protobuf:"varint,4,opt,name=total_failures,json=totalFailures,proto3" json:"total_failures,omitempty"`
	TotalTimeouts  int64                  `protobuf:"varint,5,opt,name=total_timeouts,json=totalTimeouts,proto3" json:"total_timeouts,omitempty"`
	Rps            float64                `protobuf:"fixed64,6,opt,name=rps,proto3" json:"rps,omitempty"`
	AvgLatencyMs   float64                `protobuf:"fixed64,7,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	MinLatencyMs   float64                `protobuf:"fixed64,8,opt,name=min_latency_ms,json=minLatencyMs,proto3" json:"min_latency_ms,omitempty"`
	MaxLatencyMs   float64                `protobuf:"fixed64,9,opt,name=max_latency_ms,json=maxLatencyMs,proto3" json:"max_latency_ms,omitempty"`
	P50Ms          float64                `protobuf:"fixed64,10,opt,name=p50_ms,json=p50Ms,proto3" json:"p50_ms,omitempty"`
	P90Ms          float64                `protobuf:"fixed64,11,opt,name=p90_ms,json=p90Ms,proto3" json:"p90_ms,omitempty"`
	P95Ms          float64                `protobuf:"fixed64,12,opt,name=p95_ms,json=p95Ms,proto3" json:"p95_ms,omitempty"`
	P99Ms          float64                `protobuf:"fixed64,13,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	BytesSent      int64                  `protobuf:"varint,14,opt,name=bytes_sent,json=bytesSent,proto3" json:"bytes_sent,omitempty"`
	BytesReceived  int64                  `protobuf:"varint,15,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	ActiveUsers    int32                  `protobuf:"varint,16,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AggregatedMetrics) Reset() {
	*x = AggregatedMetrics{}
	mi := &file_proto_dosloader_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetrics) ProtoMessage() {}

func (x *AggregatedMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dosloader_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetrics.ProtoReflect.Descriptor instead.
func (*AggregatedMetrics) Descriptor() ([]byte, []int) {
	return file_proto_dosloader_proto_rawDescGZIP(), []int{22}
}

func (x *AggregatedMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AggregatedMetrics) GetTotalRequests() int64 {
	if x != nil {
		return x.TotalRequests
	}
	return 0
}

func (x *AggregatedMetrics) GetTotalSuccesses() int64 {
	if x != nil {
		return x.TotalSuccesses
	}
	return 0
}

func (x *AggregatedMetrics) GetTotalFailures() int64 {
	if x != nil {
		return x.TotalFailures
	}
	return 0
}

func (x *AggregatedMetrics) GetTotalTimeouts() int64 {
	if x != nil {
		return x.TotalTimeouts
	}
	return 0
}

func (x *AggregatedMetrics) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *AggregatedMetrics) GetAvgLatencyMs() float64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetMinLatencyMs() float64 {
	if x != nil {
		return x.MinLatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetMaxLatencyMs() float64 {
	if x != nil {
		return x.MaxLatencyMs
	}
	return 0
}

func (x *AggregatedMetrics) GetP50Ms() float64 {
	if x != nil {
		return x.P50Ms
	}
	return 0
}

func (x *AggregatedMetrics) GetP90Ms() float64 {
	if x != nil {
		return x.P90Ms
	}
	return 0
}

func (x *AggregatedMetrics) GetP95Ms() float64 {
	if x != nil {
		return x.P95Ms
	}
	return 0
}

func (x *AggregatedMetrics) GetP99Ms() float64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

func (x *AggregatedMetrics) GetBytesSent() int64 {
	if x != nil {
		return x.BytesSent
	}
	return 0
}

func (x *AggregatedMetrics) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

func (x *AggregatedMetrics) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

var File_proto_dosloader_proto protoreflect.FileDescriptor

const file_proto_dosloader_proto_rawDesc = "" +
	"\n" +
	"\x15proto/dosloader.proto\x12\tdosloader\"J\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"\xf8\x02\n" +
	"\n" +
	"TestConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x14\n" +
	"\x05users\x18\x04 \x01(\x05R\x05users\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\tR\bduration\x12\x17\n" +
	"\aramp_up\x18\x06 \x01(\tR\x06rampUp\x12\x1d\n" +
	"\n" +
	"think_time\x18\a \x01(\tR\tthinkTime\x12<\n" +
	"\aheaders\x18\b \x03(\v2\".dosloader.TestConfig.HeadersEntryR\aheaders\x12\x18\n" +
	"\atimeout\x18\t \x01(\tR\atimeout\x12\x12\n" +
	"\x04body\x18\n" +
	" \x01(\fR\x04body\x12\x14\n" +
	"\x05loops\x18\v \x01(\x05R\x05loops\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x11ControllerCommand\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.dosloader.ControllerCommand.TypeR\x04type\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x15.dosloader.TestConfigR\x06config\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"2\n" +
	"\x04Type\x12\t\n" +
	"\x05START\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x02\x12\b\n" +
	"\x04STOP\x10\x03\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa9\x04\n" +
	"\vMetricsData\x12\x1a\n" +
	"\brequests\x18\x01 \x01(\x03R\brequests\x12\x1c\n" +
	"\tsuccesses\x18\x02 \x01(\x03R\tsuccesses\x12\x1a\n" +
	"\bfailures\x18\x03 \x01(\x03R\bfailures\x12\x1a\n" +
	"\btimeouts\x18\x04 \x01(\x03R\btimeouts\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x05 \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x06 \x01(\x03R\rbytesReceived\x12#\n" +
	"\rrunning_users\x18\a \x01(\x03R\frunningUsers\x12'\n" +
	"\x0fcompleted_users\x18\b \x01(\x03R\x0ecompletedUsers\x12$\n" +
	"\x0emin_latency_ns\x18\t \x01(\x03R\fminLatencyNs\x12$\n" +
	"\x0emax_latency_ns\x18\n" +
	" \x01(\x03R\fmaxLatencyNs\x12(\n" +
	"\x10total_latency_ns\x18\v \x01(\x03R\x0etotalLatencyNs\x12Y\n" +
	"\x11histogram_buckets\x18\f \x03(\v2,.dosloader.MetricsData.HistogramBucketsEntryR\x10histogramBuckets\x1aC\n" +
	"\x15HistogramBucketsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"}\n" +
	"\x0eMetricsPayload\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x120\n" +
	"\ametrics\x18\x03 \x01(\v2\x16.dosloader.MetricsDataR\ametrics\"+\n" +
	"\x0fMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x10StartTestRequest\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.dosloader.TestConfigR\x06config\"G\n" +
	"\x11StartTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10PauseTestRequest\"G\n" +
	"\x11PauseTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ResumeTestRequest\"H\n" +
	"\x12ResumeTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fStopTestRequest\"F\n" +
	"\x10StopTestResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x15\n" +
	"\x13WorkerHealthRequest\"G\n" +
	"\x14WorkerHealthResponse\x12/\n" +
	"\aworkers\x18\x01 \x03(\v2\x15.dosloader.WorkerInfoR\aworkers\"\x84\x01\n" +
	"\n" +
	"WorkerInfo\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12%\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\x03R\rlastHeartbeat\"\x12\n" +
	"\x10JobStatusRequest\"y\n" +
	"\x11JobStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x15.dosloader.TestConfigR\x06config\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\"\x15\n" +
	"\x13MetricsSubscription\"\x98\x04\n" +
	"\x11AggregatedMetrics\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0etotal_requests\x18\x02 \x01(\x03R\rtotalRequests\x12'\n" +
	"\x0ftotal_successes\x18\x03 \x01(\x03R\x0etotalSuccesses\x12%\n" +
	"\x0etotal_failures\x18\x04 \x01(\x03R\rtotalFailures\x12%\n" +
	"\x0etotal_timeouts\x18\x05 \x01(\x03R\rtotalTimeouts\x12\x10\n" +
	"\x03rps\x18\x06 \x01(\x01R\x03rps\x12$\n" +
	"\x0eavg_latency_ms\x18\a \x01(\x01R\favgLatencyMs\x12$\n" +
	"\x0emin_latency_ms\x18\b \x01(\x01R\fminLatencyMs\x12$\n" +
	"\x0emax_latency_ms\x18\t \x01(\x01R\fmaxLatencyMs\x12\x15\n" +
	"\x06p50_ms\x18\n" +
	" \x01(\x01R\x05p50Ms\x12\x15\n" +
	"\x06p90_ms\x18\v \x01(\x01R\x05p90Ms\x12\x15\n" +
	"\x06p95_ms\x18\f \x01(\x01R\x05p95Ms\x12\x15\n" +
	"\x06p99_ms\x18\r \x01(\x01R\x05p99Ms\x12\x1d\n" +
	"\n" +
	"bytes_sent\x18\x0e \x01(\x03R\tbytesSent\x12%\n" +
	"\x0ebytes_received\x18\x0f \x01(\x03R\rbytesReceived\x12!\n" +
	"\factive_users\x18\x10 \x01(\x05R\vactiveUsersB\x1cZ\x1adosloader/internal/grpc/pbb\x06proto3"

var (
	file_proto_dosloader_proto_rawDescOnce sync.Once
	file_proto_dosloader_proto_rawDescData []byte
)

func file_proto_dosloader_proto_rawDescGZIP() []byte {
	file_proto_dosloader_proto_rawDescOnce.Do(func() {
		file_proto_dosloader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dosloader_proto_rawDesc), len(file_proto_dosloader_proto_rawDesc)))
	})
	return file_proto_dosloader_proto_rawDescData
}

var file_proto_dosloader_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_dosloader_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_dosloader_proto_goTypes = []any{
	(ControllerCommand_Type)(0),  // 0: dosloader.ControllerCommand.Type
	(*RegisterRequest)(nil),      // 1: dosloader.RegisterRequest
	(*TestConfig)(nil),           // 2: dosloader.TestConfig
	(*ControllerCommand)(nil),    // 3: dosloader.ControllerCommand
	(*HeartbeatRequest)(nil),     // 4: dosloader.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 5: dosloader.HeartbeatResponse
	(*MetricsData)(nil),          // 6: dosloader.MetricsData
	(*MetricsPayload)(nil),       // 7: dosloader.MetricsPayload
	(*MetricsResponse)(nil),      // 8: dosloader.MetricsResponse
	(*StartTestRequest)(nil),     // 9: dosloader.StartTestRequest
	(*StartTestResponse)(nil),    // 10: dosloader.StartTestResponse
	(*PauseTestRequest)(nil),     // 11: dosloader.PauseTestRequest
	(*PauseTestResponse)(nil),    // 12: dosloader.PauseTestResponse
	(*ResumeTestRequest)(nil),    // 13: dosloader.ResumeTestRequest
	(*ResumeTestResponse)(nil),   // 14: dosloader.ResumeTestResponse
	(*StopTestRequest)(nil),      // 15: dosloader.StopTestRequest
	(*StopTestResponse)(nil),     // 16: dosloader.StopTestResponse
	(*WorkerHealthRequest)(nil),  // 17: dosloader.WorkerHealthRequest
	(*WorkerHealthResponse)(nil), // 18: dosloader.WorkerHealthResponse
	(*WorkerInfo)(nil),           // 19: dosloader.WorkerInfo
	(*JobStatusRequest)(nil),     // 20: dosloader.JobStatusRequest
	(*JobStatusResponse)(nil),    // 21: dosloader.JobStatusResponse
	(*MetricsSubscription)(nil),  // 22: dosloader.MetricsSubscription
	(*AggregatedMetrics)(nil),    // 23: dosloader.AggregatedMetrics
	nil,                          // 24: dosloader.TestConfig.HeadersEntry
	nil,                          // 25: dosloader.MetricsData.HistogramBucketsEntry
}
var file_proto_dosloader_proto_depIdxs = []int32{
	24, // 0: dosloader.TestConfig.headers:type_name -> dosloader.TestConfig.HeadersEntry
	0,  // 1: dosloader.ControllerCommand.type:type_name -> dosloader.ControllerCommand.Type
	2,  // 2: dosloader.ControllerCommand.config:type_name -> dosloader.TestConfig
	25, // 3: dosloader.MetricsData.histogram_buckets:type_name -> dosloader.MetricsData.HistogramBucketsEntry
	6,  // 4: dosloader.MetricsPayload.metrics:type_name -> dosloader.MetricsData
	2,  // 5: dosloader.StartTestRequest.config:type_name -> dosloader.TestConfig
	19, // 6: dosloader.WorkerHealthResponse.workers:type_name -> dosloader.WorkerInfo
	2,  // 7: dosloader.JobStatusResponse.config:type_name -> dosloader.TestConfig
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_dosloader_proto_init() }
func file_proto_dosloader_proto_init() {
	if File_proto_dosloader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dosloader_proto_rawDesc), len(file_proto_dosloader_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_dosloader_proto_goTypes,
		DependencyIndexes: file_proto_dosloader_proto_depIdxs,
		EnumInfos:         file_proto_dosloader_proto_enumTypes,
		MessageInfos:      file_proto_dosloader_proto_msgTypes,
	}.Build()
	File_proto_dosloader_proto = out.File
	file_proto_dosloader_proto_goTypes = nil
	file_proto_dosloader_proto_depIdxs = nil
}
